S3 additions for the tests
yugabyte/cdcsdk-server pull request #8
Opened 2022-06-23 16:30 UTC by vaibhav-yb

2022-06-23 16:39 UTC, vaibhav-yb commented on cdcsdk-testing/src/test/java/com/yugabyte/cdcsdk/testing/S3ConsumerRelIT.java
> +        // TestHelper.execute(createTableSql);
Commented out some statements because the next immediate step is to enable them and integrate `TestContainers`.

2022-06-24 03:46 UTC, vrajat requested changes

2022-06-24 03:46 UTC, vrajat commented on cdcsdk-testing/src/test/java/com/yugabyte/cdcsdk/testing/S3ConsumerRelIT.java
> +    @Disabled
Remove this test?

2022-06-24 03:46 UTC, vrajat commented on cdcsdk-testing/src/test/java/com/yugabyte/cdcsdk/testing/S3ConsumerRelIT.java
> +        if (!storage.bucketExists()) {
Exit or fail here?

2022-06-24 03:46 UTC, vrajat commented on cdcsdk-testing/src/test/java/com/yugabyte/cdcsdk/testing/S3ConsumerRelIT.java
> +        System.out.println("Waiting for sometime for the data to be pushed to S3...");
You can copy code that waits for number of files to appear in a location.

2022-06-24 03:46 UTC, vrajat commented on cdcsdk-testing/src/test/java/com/yugabyte/cdcsdk/testing/S3ConsumerRelIT.java
> +    private class ConfigSourceS3 {
Can you reuse S3TestConfigSourceRel instead?

2022-06-24 03:46 UTC, vrajat commented on cdcsdk-testing/src/test/java/com/yugabyte/cdcsdk/testing/S3TestConfigSourceRel.java
> +        // s3Test.put("cdcsdk.source." + StandaloneConfig.OFFSET_STORAGE_FILE_FILENAME_CONFIG,
OFFSET STORAGE should not be used. I used it in S3ConsumerIT because I was using Postgres as source.

2022-06-27 10:13 UTC, vrajat approved these changes

2022-06-27 10:15 UTC, merged